# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.6/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ilakuznecov/OOP_2381

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ilakuznecov/OOP_2381

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ilakuznecov/OOP_2381/CMakeFiles /Users/ilakuznecov/OOP_2381//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ilakuznecov/OOP_2381/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game.out

# Build rule for target.
game.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game.out
.PHONY : game.out

# fast build rule for target.
game.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/build
.PHONY : game.out/fast

Field/Cell.o: Field/Cell.cpp.o
.PHONY : Field/Cell.o

# target to build an object file
Field/Cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Cell.cpp.o
.PHONY : Field/Cell.cpp.o

Field/Cell.i: Field/Cell.cpp.i
.PHONY : Field/Cell.i

# target to preprocess a source file
Field/Cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Cell.cpp.i
.PHONY : Field/Cell.cpp.i

Field/Cell.s: Field/Cell.cpp.s
.PHONY : Field/Cell.s

# target to generate assembly for a file
Field/Cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Cell.cpp.s
.PHONY : Field/Cell.cpp.s

Field/Field.o: Field/Field.cpp.o
.PHONY : Field/Field.o

# target to build an object file
Field/Field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Field.cpp.o
.PHONY : Field/Field.cpp.o

Field/Field.i: Field/Field.cpp.i
.PHONY : Field/Field.i

# target to preprocess a source file
Field/Field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Field.cpp.i
.PHONY : Field/Field.cpp.i

Field/Field.s: Field/Field.cpp.s
.PHONY : Field/Field.s

# target to generate assembly for a file
Field/Field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Field.cpp.s
.PHONY : Field/Field.cpp.s

Inventory.o: Inventory.cpp.o
.PHONY : Inventory.o

# target to build an object file
Inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Inventory.cpp.o
.PHONY : Inventory.cpp.o

Inventory.i: Inventory.cpp.i
.PHONY : Inventory.i

# target to preprocess a source file
Inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Inventory.cpp.i
.PHONY : Inventory.cpp.i

Inventory.s: Inventory.cpp.s
.PHONY : Inventory.s

# target to generate assembly for a file
Inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Inventory.cpp.s
.PHONY : Inventory.cpp.s

Items/Flask.o: Items/Flask.cpp.o
.PHONY : Items/Flask.o

# target to build an object file
Items/Flask.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/Flask.cpp.o
.PHONY : Items/Flask.cpp.o

Items/Flask.i: Items/Flask.cpp.i
.PHONY : Items/Flask.i

# target to preprocess a source file
Items/Flask.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/Flask.cpp.i
.PHONY : Items/Flask.cpp.i

Items/Flask.s: Items/Flask.cpp.s
.PHONY : Items/Flask.s

# target to generate assembly for a file
Items/Flask.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/Flask.cpp.s
.PHONY : Items/Flask.cpp.s

Items/Item.o: Items/Item.cpp.o
.PHONY : Items/Item.o

# target to build an object file
Items/Item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/Item.cpp.o
.PHONY : Items/Item.cpp.o

Items/Item.i: Items/Item.cpp.i
.PHONY : Items/Item.i

# target to preprocess a source file
Items/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/Item.cpp.i
.PHONY : Items/Item.cpp.i

Items/Item.s: Items/Item.cpp.s
.PHONY : Items/Item.s

# target to generate assembly for a file
Items/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/Item.cpp.s
.PHONY : Items/Item.cpp.s

Items/PowerPotion.o: Items/PowerPotion.cpp.o
.PHONY : Items/PowerPotion.o

# target to build an object file
Items/PowerPotion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/PowerPotion.cpp.o
.PHONY : Items/PowerPotion.cpp.o

Items/PowerPotion.i: Items/PowerPotion.cpp.i
.PHONY : Items/PowerPotion.i

# target to preprocess a source file
Items/PowerPotion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/PowerPotion.cpp.i
.PHONY : Items/PowerPotion.cpp.i

Items/PowerPotion.s: Items/PowerPotion.cpp.s
.PHONY : Items/PowerPotion.s

# target to generate assembly for a file
Items/PowerPotion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/PowerPotion.cpp.s
.PHONY : Items/PowerPotion.cpp.s

MovementManager.o: MovementManager.cpp.o
.PHONY : MovementManager.o

# target to build an object file
MovementManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/MovementManager.cpp.o
.PHONY : MovementManager.cpp.o

MovementManager.i: MovementManager.cpp.i
.PHONY : MovementManager.i

# target to preprocess a source file
MovementManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/MovementManager.cpp.i
.PHONY : MovementManager.cpp.i

MovementManager.s: MovementManager.cpp.s
.PHONY : MovementManager.s

# target to generate assembly for a file
MovementManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/MovementManager.cpp.s
.PHONY : MovementManager.cpp.s

Player.o: Player.cpp.o
.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i
.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s
.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Player.cpp.s
.PHONY : Player.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game.out"
	@echo "... Field/Cell.o"
	@echo "... Field/Cell.i"
	@echo "... Field/Cell.s"
	@echo "... Field/Field.o"
	@echo "... Field/Field.i"
	@echo "... Field/Field.s"
	@echo "... Inventory.o"
	@echo "... Inventory.i"
	@echo "... Inventory.s"
	@echo "... Items/Flask.o"
	@echo "... Items/Flask.i"
	@echo "... Items/Flask.s"
	@echo "... Items/Item.o"
	@echo "... Items/Item.i"
	@echo "... Items/Item.s"
	@echo "... Items/PowerPotion.o"
	@echo "... Items/PowerPotion.i"
	@echo "... Items/PowerPotion.s"
	@echo "... MovementManager.o"
	@echo "... MovementManager.i"
	@echo "... MovementManager.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

