# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.6/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ilakuznecov/OOP_2381

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ilakuznecov/OOP_2381

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ilakuznecov/OOP_2381/CMakeFiles /Users/ilakuznecov/OOP_2381//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ilakuznecov/OOP_2381/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game.out

# Build rule for target.
game.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game.out
.PHONY : game.out

# fast build rule for target.
game.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/build
.PHONY : game.out/fast

# target to build an object file
Events/DefaultEvent.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Events/DefaultEvent.o
.PHONY : Events/DefaultEvent.o

# target to preprocess a source file
Events/DefaultEvent.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Events/DefaultEvent.i
.PHONY : Events/DefaultEvent.i

# target to generate assembly for a file
Events/DefaultEvent.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Events/DefaultEvent.s
.PHONY : Events/DefaultEvent.s

# target to build an object file
Events/TeleportEvent.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Events/TeleportEvent.o
.PHONY : Events/TeleportEvent.o

# target to preprocess a source file
Events/TeleportEvent.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Events/TeleportEvent.i
.PHONY : Events/TeleportEvent.i

# target to generate assembly for a file
Events/TeleportEvent.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Events/TeleportEvent.s
.PHONY : Events/TeleportEvent.s

# target to build an object file
Events/TrapEvent.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Events/TrapEvent.o
.PHONY : Events/TrapEvent.o

# target to preprocess a source file
Events/TrapEvent.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Events/TrapEvent.i
.PHONY : Events/TrapEvent.i

# target to generate assembly for a file
Events/TrapEvent.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Events/TrapEvent.s
.PHONY : Events/TrapEvent.s

# target to build an object file
Events/TreatEvent.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Events/TreatEvent.o
.PHONY : Events/TreatEvent.o

# target to preprocess a source file
Events/TreatEvent.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Events/TreatEvent.i
.PHONY : Events/TreatEvent.i

# target to generate assembly for a file
Events/TreatEvent.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Events/TreatEvent.s
.PHONY : Events/TreatEvent.s

# target to build an object file
Field/Cell.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Cell.o
.PHONY : Field/Cell.o

# target to preprocess a source file
Field/Cell.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Cell.i
.PHONY : Field/Cell.i

# target to generate assembly for a file
Field/Cell.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Cell.s
.PHONY : Field/Cell.s

# target to build an object file
Field/Field.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Field.o
.PHONY : Field/Field.o

# target to preprocess a source file
Field/Field.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Field.i
.PHONY : Field/Field.i

# target to generate assembly for a file
Field/Field.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Field.s
.PHONY : Field/Field.s

# target to build an object file
Field/FieldCreator.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/FieldCreator.o
.PHONY : Field/FieldCreator.o

# target to preprocess a source file
Field/FieldCreator.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/FieldCreator.i
.PHONY : Field/FieldCreator.i

# target to generate assembly for a file
Field/FieldCreator.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/FieldCreator.s
.PHONY : Field/FieldCreator.s

# target to build an object file
Game/GameManager.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Game/GameManager.o
.PHONY : Game/GameManager.o

# target to preprocess a source file
Game/GameManager.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Game/GameManager.i
.PHONY : Game/GameManager.i

# target to generate assembly for a file
Game/GameManager.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Game/GameManager.s
.PHONY : Game/GameManager.s

# target to build an object file
Input/Input.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Input/Input.o
.PHONY : Input/Input.o

# target to preprocess a source file
Input/Input.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Input/Input.i
.PHONY : Input/Input.i

# target to generate assembly for a file
Input/Input.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Input/Input.s
.PHONY : Input/Input.s

# target to build an object file
Inventory.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Inventory.o
.PHONY : Inventory.o

# target to preprocess a source file
Inventory.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Inventory.i
.PHONY : Inventory.i

# target to generate assembly for a file
Inventory.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Inventory.s
.PHONY : Inventory.s

# target to build an object file
Items/Flask.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/Flask.o
.PHONY : Items/Flask.o

# target to preprocess a source file
Items/Flask.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/Flask.i
.PHONY : Items/Flask.i

# target to generate assembly for a file
Items/Flask.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/Flask.s
.PHONY : Items/Flask.s

# target to build an object file
Items/Item.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/Item.o
.PHONY : Items/Item.o

# target to preprocess a source file
Items/Item.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/Item.i
.PHONY : Items/Item.i

# target to generate assembly for a file
Items/Item.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/Item.s
.PHONY : Items/Item.s

# target to build an object file
Items/PowerPotion.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/PowerPotion.o
.PHONY : Items/PowerPotion.o

# target to preprocess a source file
Items/PowerPotion.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/PowerPotion.i
.PHONY : Items/PowerPotion.i

# target to generate assembly for a file
Items/PowerPotion.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Items/PowerPotion.s
.PHONY : Items/PowerPotion.s

# target to build an object file
MovementManager.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/MovementManager.o
.PHONY : MovementManager.o

# target to preprocess a source file
MovementManager.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/MovementManager.i
.PHONY : MovementManager.i

# target to generate assembly for a file
MovementManager.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/MovementManager.s
.PHONY : MovementManager.s

# target to build an object file
Player.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Player.o
.PHONY : Player.o

# target to preprocess a source file
Player.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Player.i
.PHONY : Player.i

# target to generate assembly for a file
Player.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Player.s
.PHONY : Player.s

# target to build an object file
main.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/main.s
.PHONY : main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game.out"
	@echo "... Events/DefaultEvent.o"
	@echo "... Events/DefaultEvent.i"
	@echo "... Events/DefaultEvent.s"
	@echo "... Events/TeleportEvent.o"
	@echo "... Events/TeleportEvent.i"
	@echo "... Events/TeleportEvent.s"
	@echo "... Events/TrapEvent.o"
	@echo "... Events/TrapEvent.i"
	@echo "... Events/TrapEvent.s"
	@echo "... Events/TreatEvent.o"
	@echo "... Events/TreatEvent.i"
	@echo "... Events/TreatEvent.s"
	@echo "... Field/Cell.o"
	@echo "... Field/Cell.i"
	@echo "... Field/Cell.s"
	@echo "... Field/Field.o"
	@echo "... Field/Field.i"
	@echo "... Field/Field.s"
	@echo "... Field/FieldCreator.o"
	@echo "... Field/FieldCreator.i"
	@echo "... Field/FieldCreator.s"
	@echo "... Game/GameManager.o"
	@echo "... Game/GameManager.i"
	@echo "... Game/GameManager.s"
	@echo "... Input/Input.o"
	@echo "... Input/Input.i"
	@echo "... Input/Input.s"
	@echo "... Inventory.o"
	@echo "... Inventory.i"
	@echo "... Inventory.s"
	@echo "... Items/Flask.o"
	@echo "... Items/Flask.i"
	@echo "... Items/Flask.s"
	@echo "... Items/Item.o"
	@echo "... Items/Item.i"
	@echo "... Items/Item.s"
	@echo "... Items/PowerPotion.o"
	@echo "... Items/PowerPotion.i"
	@echo "... Items/PowerPotion.s"
	@echo "... MovementManager.o"
	@echo "... MovementManager.i"
	@echo "... MovementManager.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

